#!/usr/bin/env bash

# Convenient GPG encryption and decryption
# Source: https://github.com/Czocher/gpg-crypt

# Decrypt the given tar.gpg file
function gpg-decrypt() {
  if [ "$#" -ne 1  ] || [[ "$1" != *.tar.gpg ]]; then
    echo "Usage: $0 FILE.tar.gpg" >&2
    return 1
  fi

  gpg --quiet --decrypt $1 | tar -x
}

gpg-decrypt "$@"
