#!/usr/bin/env bash

# List internal and external ip addresses

myip() {
    local GREEN="\e[32m"
    local CYAN='\033[0;36m'
    local NOCOLOR="\e[0m"

    printf "Internal IP addresses:\n${GREEN}%s${NOCOLOR}\n" "$(ifconfig | grep "inet " | awk '{ print $2 }')"
    printf "External IP address:\n${CYAN}%s${NOCOLOR}\n" "$(dig +short myip.opendns.com @resolver4.opendns.com)"
}

myip "$@"
