#!/usr/bin/env zsh

# point dns nameserver to localhost

resumedns() {
    echo "\
nameserver 127.0.0.1
nameserver ::1
options trust-ad edns0 single-request-reopen" | sudo tee /etc/resolv.conf >/dev/null

    sudo systemctl restart dnscrypt-proxy pihole-FTL NetworkManager
}
