#!/usr/bin/env sh

# swaps the names of two files

swapname() {
    tcc -run - "$@" <<"CODE"
    #include <unistd.h>
    #include <fcntl.h>
    #include <stdio.h>
    #include <sys/syscall.h>

    int local_RENAME_EXCHANGE = (1 << 1);

    int main(int argc, char **argv) {
        if (argc != 3) {
            fprintf(stderr, "Error: Could not swap file names. Usage: %s PATH1 PATH2\n", argv[0]);
            return 2;
        }
        int r = syscall(
            SYS_renameat2,
            AT_FDCWD, argv[1],
            AT_FDCWD, argv[2],
            local_RENAME_EXCHANGE
        );
        if (r < 0) {
            perror("Error: Could not swap file names.");
            return 1;
        }
        else return 0;
    }
CODE
}

swapname "$@"
