#!/usr/bin/env sh

# Download highest quality youtube audio
yta() {
    yt-dlp \
        --format 'ba' \
        --extract-audio \
        --audio-quality 0 \
        --audio-format 'opus' \
        --format-sort 'abr,asr' \
        --output "$HOME/Music/youtube/%(title)s.%(ext)s" \
        "$@"
}

yta "$@"
