#!/usr/bin/env bash
# -*- coding: utf-8 -*-

usage() {
    cat >&2 <<-EOF
    Usage: $(basename -- "${BASH_SOURCE:-$0}") [options] url
    Download highest quality audio from YouTube.
EOF
}

# Download highest quality youtube audio
yta() {

    if [ "$#" -gt 0 ]; then
        local __FORMAT='ba'
        local __OUTPUT="$HOME/Audio/youtube/%(title)s.%(ext)s"
        local __OUTPUT_FORMAT='opus'
        local __AUDIO_QUALITY=0
        local __SORT_ORDER='abr,asr'
        local __CONFIG_PATH="$HOME/.config/yt-dlp/config"
        local __LOG_PATH="$HOME/.local/share/yt-dlp/logs/audio"
        local __LOG_FILE="$__LOG_PATH/$(date +'%F--%T').log"

        yt-dlp \
            --extract-audio \
            --format "$__FORMAT" \
            --audio-quality "$__AUDIO_QUALITY" \
            --audio-format "$__OUTPUT_FORMAT" \
            --format-sort "$__SORT_ORDER" \
            --output "$__OUTPUT" \
            --config-location "$__CONFIG_PATH" \
            "$@" 2> "$__LOG_FILE"

        printf \
            "${c[green]}👍 Successfully ${c[reset]} downloaded as ${c[light_blue]} %s ${c[reset]}\n" \
            "$(/bin/ls -Art "$(dirname "$__OUTPUT")" | tail -n 1)"
    else
        usage
    fi
}

yta "$@"
