#!/usr/bin/env bash
# -*- coding: utf-8 -*-

usage() {
    cat >&2 <<-EOF
    Usage: $(basename -- "${BASH_SOURCE:-$0}") [options] url

    Download videos from YouTube in the highest quality possible.
    Video sources are sorted by their specifications in the following order:
    ${c[light_blue]} RESOLUTION, VIDEO_BIT_RATE, AUDIO_SAMPLING_RATE, AUDIO_BIT_RATE ${c[reset]}
EOF
}

# Download highest quality youtube video
yt_archive() {
    # restrict_mp4_format="bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"
    # best_quality_format='bv*+ba/b'

    if [ "$#" -gt 0 ]; then
        local __FORMAT='bv*+ba/b'
        local __OUTPUT="$HOME/Videos/Archive/%(title)s.%(ext)s"
        local __SORT_ORDER='res,vbr,abr,asr'
        local __CONFIG_PATH="$HOME/.config/yt-dlp/archive.video.config"
        local __LOG_PATH="$HOME/.local/share/yt-dlp/logs/archive"
        local __LOG_FILE="$__LOG_PATH/ytarchive__$(date +'%F--%T').log"

        yt-dlp \
            --config-location "$__CONFIG_PATH" \
            --format "$__FORMAT" \
            --format-sort "$__SORT_ORDER" \
            --output "$__OUTPUT" \
            "$@" 2> "$__LOG_FILE"

        printf \
            "${c[green]}Successfully ${c[reset]} downloaded as ${c[light_blue]} %s. ${c[reset]}\n" \
            "$(/bin/ls -Art "$(dirname "$__OUTPUT")" | tail -n 1)"
    else
        usage
    fi
}

yt_archive "$@"
