#!/usr/bin/env sh

SCRIPTDIR="$ZCONFDIR/functions"

# Download highest quality youtube video in mp4
ytv() {
    # restrict_mp4_format="bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"
    # best_quality_format='bv*+ba/b'

    format='bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b'
    output="$HOME/Videos/youtube/%(title)s.%(ext)s"
    config_path="$HOME/.config/yt-dlp/config"

    yt-dlp \
        --config-location "$config_path" \
        --format "$format" \
        --output "$output" \
        "$@"

    "$SCRIPTDIR/lib/__to_mp4" "$(dirname "$output")"
}

ytv "$@"
