#!/usr/bin/env bash
# -*- coding: utf-8 -*-

#
# decrypt
# linearize
#
#

usage() {
    cat >&2 <<-EOF
    Usage: $(basename -- "${BASH_SOURCE:-$0}") [options] [args]
    PDF manipulation tools.
EOF
}

__backup() {
   cp "$1" "${1}.backup"
}

_decrypt() {
    src="${1}.backup"
    dest="${1}"

    stty -echo
    echo -n "Enter decryption password: "
    read password
    echo

    mv "$1" "${1}.backup"
    qpdf \
        --decrypt \
        --password="$password" \
        "${1}.backup" "${1}"

    echo -e "\nDecryption successful."

    stty echo
}

_rm_metadata() {
    __backup "$1"

    exiftool -overwrite_original -all:all= "$src"
}

_linearize() {
    _rm_metadata "$1"

    qpdf \
        --optimize-images \
        --linearize \
        "$1" -- "_${1}"

    mv -f "_${1}" "$1"

    echo -e "\nLinearization successful."
}

_images() {
    img2pdf --output "${1%.*}.pdf" --pagesize A4 "${@:2}"
    echo -e "\nPDF created successful."
}

_text() {
    pdftotext -layout "$1" "${1%.*}.txt"
}

_concat() {
    qpdf --optimize-images --linearize --empty --pages "${@:2}"
}

_compress() {
    exiftool -overwrite_original -all:all= "$1"
    mv "$1" "${1}.bkp"
    qpdf --linearize --empty --pages "${1}.bkp" -- "$1"
    rm -f "${1}.bkp"
}

main() {
    if [ $# -gt 0 ]; then
        if [[ -z "$1" ]] || [[ -z "$2" ]]; then
            usage
        fi

        case "$1" in
            -c|--concat)
                _concat "${@:2}"
                ;;
            -d|--decrypt)
                _decrypt "${@:2}"
                ;;
            -l|--linearize)
                _linearize "${@:2}"
                ;;
            -c|--compress)
                _compress "${@:2}"
                ;;
            -i|--images)
                _images "${@:2}"
                ;;
            -t|--text)
                _text "${@:2}"
                ;;
            -h|--help)
                usage
                ;;
            *)
                usage
                ;;
        esac
    fi
}

main "$@"
