#!/usr/bin/env bash

# Refresh pacman mirrors
refmirr() {
	TMPFILE=$(mktemp)

	# Save new mirrorlist to temp
	rate-mirrors \
		--save=$TMPFILE \
		--disable-comments-in-file \
		--concurrency 16 \
		--entry-country DE \
		--country-neighbors-per-country 8 \
		--country-test-mirrors-per-country 8 \
		--top-mirrors-number-to-retest 16 \
		--max-jumps 8 \
		--protocol https \
		arch \
		--sort-mirrors-by score_asc \
		--max-delay 21600

	# Replace mirrorlist
	sudo mv /etc/pacman.d/mirrorlist{,.old}
	sudo mv "$TMPFILE" /etc/pacman.d/mirrorlist
}
