#!/usr/bin/env sh

# Aliases

# Services
alias reloadde="plasmashell --replace && kwin_x11 --replace  >/dev/null 2>&1"
alias reloaddns="sudo systemctl restart dnscrypt-proxy pihole-FTL NetworkManager"

# Arch package management
alias y="yay" # Or just `yay`
alias yf="yay -Syu --noconfirm"
alias yayf="yay -Syu --noconfirm"
alias yup="yay -Syyu"
alias yupf="yay -Syyu --noconfirm"
alias ys="yay -S"
alias yy="yay -S --noconfirm" # Install / Reinstall
alias yyy="yay -S --noconfirm --needed" # Install if required
alias yr="yay -R" # Uninstall
alias yrr="yay -Rns" # Uninstall / Remove completely / Purge
alias yrrr="yay -Rns --noconfirm" # Uninstall / Remove completely / Purge non-interactively
alias yfd="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"
alias yrm="yay -Qq | fzf --multi --preview 'yay -Qi {1}' | xargs -ro sudo yay -Rns"

# Text
alias cpy="xsel -bi" # Copy to clipboard
alias pst="xsel -bo" # Paste from clipboard

# Fonts
alias fontcc='fc-cache -f'
alias fontm='fc-match'

# Utility
alias now="date +\"%r\""
alias today="date +%F"
alias fastping="ping -c 100 -s.2"
alias open="xdg-open 2>/dev/null"
alias netcon="sudo arp-scan -l"

# Misc
alias sudokate="SUDO_EDITOR=kate sudoedit" # launch kate as root
alias refreshmirrors="sudo systemctl start reflector"

# Shortcuts
alias ~="cd $HOME"
alias conf="cd $CONFIG"
alias fjson="python -m json.tool"

# exa
alias exa="exa --git --icons --group --color-scale --time-style=long-iso --group-directories-first"
alias exaa="exa --all"
alias exal="exa --long"
alias exaal="exa --all --long"

# Safety
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias ln="ln -i"

# TeX
# TeX Live Package Manager (pacman integration)
alias texpac="tllocalmgr"

## Config file shortcuts

# Edit shortcuts
alias nvimrc='nvim ~/.config/nvim/init.vim'
alias zshrc='nvim ~/.zshrc'
alias zprofile='nvim ~/.zprofile'
alias zshenv='nvim ~/.zshenv'
alias foxrc='nvim ~/.mozilla/firefox/nightly/user.js'
alias yayrc='nvim ~/.config/yay/config.json'
alias starrc='nvim ~/.zsh/themes/starship.toml'

# Root
alias dnscryptrc='nvim /etc/dnscrypt-proxy/dnscrypt-proxy.toml'
alias ftlrc='nvim /etc/pihole/pihole-FTL.conf'
alias resolvrc='nvim /etc/resolv.conf'
alias pacmanrc='nvim /etc/pacman.conf'
alias makepkgrc='nvim /etc/makepkg.conf'
alias nginxrc='nvim /etc/nginx/nginx.conf'
alias piholerc='nvim /etc/pihole/pihole-FTL.conf'

# Text editing
alias snvim="sudo nvim"
alias svim="sudo vim"
alias svi="sudo vi"
alias snano="sudo nano"

# download
alias ytaudio='youtube-dl -i --extract-audio --audio-format mp3 --audio-quality 0 -o "~/Music/%(title)s.%(ext)s"'

