#!/usr/bin/env sh

# Aliases

# Services
alias reloadde="systemctl --user restart plasma-plasmashell"
alias reloaddns="sudo systemctl restart dnscrypt-proxy pihole-FTL NetworkManager"

# Arch
alias yayy="yay -S --needed --noconfirm" # Install
alias yayr="yay -Rns" # Uninstall / Remove completely / Purge
alias refreshmirrors="sudo reflector --latest 200 --protocol https --sort rate --fastest 50 --save /etc/pacman.d/mirrorlist > /dev/null 2>&1"

# Text
alias cpy="xsel -bi" # Copy to clipboard
alias pst="xsel -bo" # Paste from clipboard
alias sudokate="SUDO_EDITOR=kate sudoedit"

# Utility
alias lsh="ls -d .*"
alias now="date +\"%r\""
alias today="date +%F"
alias fastping="ping -c 100 -s.2"

# Shortcuts
alias ~="cd $HOME"
alias fjson="python -m json.tool"

# Safety
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias ln="ln -i"
