# aria2-next configuration

## Console
quiet=false
console-log-level=error
summary-interval=1
enable-color=true
download-result=full
show-console-readout=true
truncate-console-readout=true

## Network
disable-ipv6=true
timeout=60
connect-timeout=30
max-tries=0
retry-wait=5
remote-time=true
continue=true
no-netrc=true

## Downloading
stream-max-connections=16
max-concurrent-downloads=16
optimize-concurrent-downloads=true
max-file-not-found=1

## Disk
allow-overwrite=false
auto-file-renaming=false
file-allocation=falloc
