#!/usr/bin/env bash

__to_mp4_force() {
    # $1 = dir_name
    output_file="$(/bin/ls -Art "$1" | tail -n 1)"
    output_file_name="${output_file%.*}"

    echo -e " **---- $output_file to ${output_file_name}.mp4... ----** "

    ffmpeg -y \
        -i "${1}/${output_file}" \
        -c:v h264_nvenc -preset slow \
        -c:a libfdk_aac -cutoff 20000 -afterburner 1 -vbr 0 \
        "${1}/${output_file_name}_transcoded.mp4" 2> /dev/null

    echo "Deleting ${1}/${output_file_name}"
    rm -f "${1}/${output_file_name}.mp4"

    echo -e "Transcoded file stored at ${1}/${output_file_name}_transcoded.mp4"
}

__to_mp4_force "$@"
