color0 #061e37
color1 #fd4663
color2 #5ea4ed
color3 #da6bc4
color4 #9b47eb
color5 #8cbef2
color6 #e996d8
color7 #f2f2f3
color8 #5f6974
color9 #fd4663
color10 #5ea4ed
color11 #da6bc4
color12 #9b47eb
color13 #8cbef2
color14 #e996d8
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #061e37
background            #061e37
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #082849
active_border_color   #5ea4ed
inactive_border_color #082849
url_color             #5ea4ed

active_tab_foreground   #101519
active_tab_background   #5ea4ed
inactive_tab_foreground #afb2b6
inactive_tab_background #082849
cursor_trail_color      #afb2b6
