color0 #0c0d31
color1 #fd4663
color2 #9094eb
color3 #ba95e6
color4 #e295e6
color5 #9397ec
color6 #bc96e9
color7 #f2f2f3
color8 #5e5f72
color9 #fd4663
color10 #9094eb
color11 #ba95e6
color12 #e295e6
color13 #9397ec
color14 #bc96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0c0d31
background            #0c0d31
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #101242
active_border_color   #9094eb
inactive_border_color #101242
url_color             #9094eb

active_tab_foreground   #0d0d14
active_tab_background   #9094eb
inactive_tab_foreground #afafb6
inactive_tab_background #101242
cursor_trail_color      #afafb6
