#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# Scene rules:
#
# ffmpeg -i input.mp4 \
# -c:v libx264 -crf 19 -level 3.1 -preset slow -tune film \
# -filter:v scale=-1:720 -sws_flags lanczos \
# -c:a libfdk_aac -vbr 5 \
# output.mp4

__to_mp4_force() {
    # $1 = dir_name
    output_file="$(/bin/ls -Art "$1" | tail -n 1)"
    output_file_name="${output_file%.*}"


    # "$HOME/.config/zsh/functions/lib/__print_in_block" "Transcoding" "${output_file}."

    #      ffmpeg -y \
    #          -v quiet -stats \
    #          -i "${1}/${output_file}" \
    #          -c:v h264_nvenc -preset slow \
    #          -c:a libfdk_aac -cutoff 20000 -afterburner 1 -vbr 0 \
    #          "${1}/${output_file_name}_transcoded.mp4" 2> /dev/null

    #     ffmpeg -y \
    #         -v quiet -stats \
    #         -i "${1}/${output_file}" \
    #         -c:v libx264 -preset veryfast \
    #         -c:a libfdk_aac -cutoff 20000 -afterburner 1 -vbr 0 \
    #         "${1}/${output_file_name}_transcoded.mp4" 2> /dev/null

    local __LOG_PATH="$HOME/.local/share/ffmpeg/logs/transcode"
    local __LOG_FILE="$__LOG_PATH/ffmpeg_TC__$(date +'%F--%T').log"

    revolver stop &>/dev/null
    revolver --style 'dots2' start "Transcoding ${output_file:0:100}."

#     ffmpeg -y \
#         -v quiet -stats \
#         -i "${1}/${output_file}" \
#         -map_metadata 0 \
#         -movflags use_metadata_tags \
#         -c:v libx264 -crf 24 -preset veryfast -tune film \
#         -filter:v scale=-1:720 -sws_flags lanczos \
#         -c:a libfdk_aac -cutoff 20000 -afterburner 1 -vbr 3 \
#         "${1}/${output_file_name}__TC.mp4" 2>"$__LOG_FILE"

    ffmpeg -y \
        -v quiet -stats \
        -i "${1}/${output_file}" \
        -map_metadata 0 \
        -movflags +use_metadata_tags \
        -c:v libx264 -crf 26 \
        -preset veryfast -tune film -pix_fmt yuv420p \
        -filter:v scale="iw/1.5:-2" -sws_flags lanczos \
        -movflags +faststart \
        -c:a libfdk_aac -cutoff 18000 -afterburner 1 -vbr 5 \
        "${1}/${output_file_name}__TC.mp4" 2>"$__LOG_FILE"

    if (($? == 0)); then
        revolver --style 'dots2' update "Transcode successfull - ${1}/${output_file_name}.mp4"
        revolver --style 'dots2' update "Deleting ${1}/${output_file}"
        rm -f "${1}/${output_file}"
        mv "${1}/${output_file_name}_.mp4" "${1}/${output_file_name}.mp4"
        revolver stop
        echo -e "Stored at: ${LIGHTGREEN}${1}/${output_file_name}.mp4${NOCOLOR}"
    else
        revolver --style 'dots2' update "Transcode unsuccessful."
        revolver stop
    fi


    # rm -f "${1}/${output_file_name}.mp4"

    # "$HOME/.config/zsh/functions/lib/__print_in_block" "Transcoded file stored at" "${LIGHTGREEN}${1}/${output_file_name}.mp4${NOCOLOR}"
}

__to_mp4_force "$@"
