# ~/.config/hypr/hyprland.conf
#
# Main configuration file

# ==========================================
# MODULAR CONFIGURATION
# ==========================================
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/keywords.conf
source = ~/.config/hypr/conf.d/environment.conf
source = ~/.config/hypr/conf.d/variables.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/windows.conf
source = ~/.config/hypr/conf.d/layers.conf
source = ~/.config/hypr/conf.d/plugins.conf
